### 회원가입
POST http://localhost:8081/api/auth/signUp
Content-Type: application/json

{
  "email" : "test@test.com",
  "userId" : "test",
  "password" : "test"
}

### 로그인
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email" : "test@test.com",
  "password" : "test"
}

