server:
  port: 8080
logging:
  level:
    org:
      timeline_blog: DEBUG
      hibernate:
        type:
          EnumType: TRACE
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:h2:mem:callblog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2: # h2 web 접속여부 ~/h2
    console:
      enabled: true
      path: /h2
      settings:
        trace: true