spring:
  profiles:
    include: "db"
    group:
      dev: "common,dev"
      local: "common,local"

---

spring:
  config:
    activate:
      on-profile: "common"

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace #sql (Bind Parameter) 출력
#            BasicBinder: trace
#            EnumType: trace
