spring:
  config:
    activate:
      on-profile: "dev"

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:h2:mem:housebook-local
    username: sa
    password:
    driver-class-name: org.h2.Driver

---

spring:
  config:
    activate:
      on-profile: "local"

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
#    url: jdbc:h2:mem:housebook-local
    url: jdbc:h2:tcp://localhost/~/callblog-local
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
